spring:
  application:
    name: catalog-service
  devtools:
    restart.enabled: true # DEV_ENV
    livereload.port: 35731
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      # retry
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: devops
    password: devops+postgresql
    url: jdbc:postgresql://localhost:5432/devops
    # KikariCP connection pool
    connection-timeout: 2000
    maximum-pool-size: 5
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/bookstore

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

logging:
  level:
    com.spike.spring.catalog: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh

