[webservers]
; DEPLOY_ENV
testserver ansible_port=22

[webservers:vars]
; ansible_host=127.0.0.1
; DEPLOY_ENV: vagrant ssh
ansible_host=10.50.1.83
ansible_user=vagrant
ansible_private_key_file=.vagrant/machines/default/virtualbox/private_key