version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: "always"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devops-network

  postgresql:
    image: postgres:16.2
    container_name: postgresql
    restart: "always"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - devops-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: "always"
    env_file:
      - .env
    ports:
      - 5433:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - devops-network
    depends_on:
      postgresql:
        condition: service_healthy

  mongo:
    container_name: mongo
    image: mongo:6.0.1
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    networks:
      - devops-network
    volumes:
      - "./data/mongodb:/data/db"
      - "./init/mongodb:/docker-entrypoint-initdb.d"

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    restart: always
    env_file:
      - .env
    ports:
      - '27018:8081'
    depends_on:
      - mongo
    networks:
      - devops-network

  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    restart: "always"
    env_file:
      - .env
    ports:
#      - 61616:61616
      - 5672:5672
      - 18161:8161
    volumes:
      - ./data/activemq:/var/lib/artemis-instance
    networks:
      - devops-network

  # apache/kafka:3.7.0: https://hub.docker.com/r/apache/kafka
  kafka-broker:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    restart: "always"
    ports:
      - 9092:9092
    networks:
      - devops-network

networks:
  devops-network:
    external: true
