/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spike.eventstreams;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String servers = "localhost:9092";
        String groupId = "app";
        String inTopic = "raw-events";
        String goodTopic = "enriched-events";

        Consumer consumer = new Consumer(servers, groupId, inTopic);
        PassthruProducer producer = new PassthruProducer(servers, goodTopic);
        consumer.run(producer);
    }
}
