/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spike.eventstreams;

import com.spike.eventstreams.nile.Consumer;
import com.spike.eventstreams.nile.DomainService;
import com.spike.eventstreams.nile.FullProducer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static interface Topics {
        String RAW_EVENTS = "raw-events";
        String BAD_EVENTS = "bad-events";
        String ENRICHED_EVENTS = "enriched-events";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String servers = "localhost:9092";
        String groupId = "app";
        String inTopic = "raw-events";
        String goodTopic = "enriched-events";
        String badTopic = "bad-events";

        Consumer consumer = new Consumer(servers, groupId, inTopic);
//        PassthruProducer producer = new PassthruProducer(servers, goodTopic);
        FullProducer producer = new FullProducer(servers, goodTopic, badTopic, new DomainService());
        consumer.run(producer);
    }
}
