/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "vertx-in-action-application"
include("user-profile-service")
include("ingestion-service")
include("activity-service")
include("public-api")
include("event-stats-service")
include("congrats-service")
include("commons")
include("dashboard-webapp")
include("user-webapp")
