spring:
  application:
    name: dispatcher-service
  devtools:
    restart.enabled: true # DEV_ENV
    livereload.port: 35734

server:
  port: 9004
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

logging:
  level:
    com.spike.spring.dispatcher: DEBUG