# group: webservers
[webservers]
; DEPLOY_ENV
testserver ansible_port=22

[webservers:vars]
# DEPLOY_ENV
ansible_host=10.50.1.93
ansible_user=vagrant
ansible_private_key_file=.vagrant/machines/default/virtualbox/private_key